# Generated by Django 3.0.6 on 2020-12-23 05:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0087_merge_20201022_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('campaign', 'Campaign')], max_length=10)),
                ('category', models.CharField(choices=[('realtime', 'Realtime'), ('consolidate', 'Consolidate')], max_length=12)),
                ('commission_category', models.CharField(choices=[('fixed', 'Fixed'), ('range', 'Range'), ('product', 'Product')], max_length=8)),
                ('client_rule', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('engine_rule', django.contrib.postgres.fields.jsonb.JSONField(default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated',),
                'permissions': (('manage_rules', 'Manage rules'),),
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='pending', max_length=32)),
                ('rule_category', models.CharField(choices=[('realtime', 'Realtime'), ('consolidate', 'Consolidate')], default='realtime', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='order.Order')),
                ('rules', models.ManyToManyField(blank=True, related_name='commission_rules', to='commission.Rule')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated',),
                'permissions': (('manage_commissions', 'Manage commissions.'),),
            },
        ),
    ]
