# Generated by Django 3.0.6 on 2020-12-27 08:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='client_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='commission_category',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('range', 'Range'), ('product', 'Product')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rule',
            name='engine_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
    ]
