# Generated by Django 3.0.6 on 2020-12-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_userprofile'),
        ('commission', '0002_auto_20201227_1407'),
    ]

    operations = [
    ]
