# Generated by Django 3.0.6 on 2021-01-04 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0003_merge_20201230_1016'),
        ('commission', '0004_rule_deleted_at'),
    ]

    operations = [
    ]
