# Generated by Django 3.0.6 on 2021-01-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0005_merge_20210104_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulehistory',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='commission.Rule'),
        ),
    ]
