# Generated by Django 3.0.6 on 2021-02-14 06:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_auto_20210111_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder),
        ),
    ]
