# Generated by Django 3.0.6 on 2021-02-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_auto_20210214_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at=None), fields=('name',), name='unique_name'),
        ),
    ]
