# Generated by Django 3.0.6 on 2021-05-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_auto_20210224_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='rule_category',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='rules',
        ),
        migrations.AddField(
            model_name='commission',
            name='rule_history',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commission.RuleHistory'),
        ),
        migrations.AlterField(
            model_name='rulehistory',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commission_rules', to='commission.Rule'),
        ),
    ]
