# Generated by Django 3.0.6 on 2021-05-30 20:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0010_auto_20210527_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='client_rule',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='engine_rule',
        ),
        migrations.AlterField(
            model_name='rulehistory',
            name='client_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='rulehistory',
            name='engine_rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, editable=False, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='rulehistory',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rule_histories', to='commission.Rule'),
        ),
    ]
