# Generated by Django 3.0.6 on 2021-06-01 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0011_auto_20210126_1049'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0011_auto_20210530_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='status',
        ),
        migrations.CreateModel(
            name='CommissionServiceMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('done', 'Done')], default='pending', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_service_month', to='partner.Partner')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_service_month', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-month',),
                'unique_together': {('service', 'month', 'user')},
            },
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_service_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='commission.CommissionServiceMonth'),
        ),
    ]
