# Generated by Django 3.0.6 on 2021-07-13 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0012_auto_20210601_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
