# Generated by Django 3.0.6 on 2020-10-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='details',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
