# Generated by Django 3.0.6 on 2020-10-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20201019_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',), 'permissions': (('manage_notifications', 'Manage notifications.'),), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='segment',
            options={'ordering': ('-created',), 'verbose_name': 'segment', 'verbose_name_plural': 'segments'},
        ),
    ]
