# Generated by Django 3.0.6 on 2021-10-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20201029_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notification',
            new_name='Announcement',
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',), 'permissions': (('manage_announcements', 'Manage announcements.'),), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
