# Generated by Django 3.0.6 on 2021-10-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20211010_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',), 'permissions': (('manage_announcements', 'Manage announcements.'), ('view_announcements', 'View announcements.')), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
