# Generated by Django 3.0.6 on 2021-10-17 13:04

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0006_auto_20211010_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('type', models.CharField(choices=[('agent_request_submitted', 'Agent request submitted'), ('agent_request_processed', 'Agent request processed'), ('partner_added', 'Partner added'), ('target_set ', 'Target set'), ('commission_rule_created', 'Commission rule created'), ('commission_rule_updated', 'Commission rule updated'), ('user_correction_request_submitted', 'User correction request submitted'), ('user_correction_request_processed', 'User correction request processed'), ('notice_created', 'Notice created'), ('order_created', 'Order created')], max_length=64)),
                ('user_group', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user_region', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user_profile', models.CharField(blank=True, max_length=128, null=True)),
                ('path', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ('-created',),
                'permissions': (('manage_notifications', 'Manage notifications.'),),
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-created',), 'permissions': (('manage_announcements', 'Manage announcements.'), ('view_announcements', 'View announcements.')), 'verbose_name': 'announcement', 'verbose_name_plural': 'announcement'},
        ),
        migrations.CreateModel(
            name='NotificationMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=saleor.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.Notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification_meta',
                'verbose_name_plural': 'notifications_meta',
                'permissions': (('manage_notifications', 'Manage notifications.'),),
            },
        ),
    ]
