# Generated by Django 3.0.6 on 2021-10-25 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_auto_20210823_1652'),
        ('commission', '0013_commission_deleted_at'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0008_auto_20211024_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_group',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_profile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_region',
        ),
        migrations.AddField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(null=True, related_name='group_notifications', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='profiles',
            field=models.ManyToManyField(null=True, related_name='profile_notifications', to='commission.UserProfile'),
        ),
        migrations.AddField(
            model_name='notification',
            name='regions',
            field=models.ManyToManyField(null=True, related_name='region_notifications', to='account.Region'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.AddField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(null=True, related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('agent_request_submitted', 'Agent request submitted'), ('agent_request_processed', 'Agent request processed'), ('partner_added', 'Partner added'), ('target_set ', 'Target set'), ('user_correction_request_submitted', 'User correction request submitted'), ('user_correction_request_processed', 'User correction request processed'), ('notice_created', 'Notice created'), ('order_created', 'Order created')], max_length=64),
        ),
    ]
