# Generated by Django 3.0.6 on 2021-10-25 13:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0013_commission_deleted_at'),
        ('account', '0085_auto_20210823_1652'),
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0009_auto_20211025_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='groups',
            field=models.ManyToManyField(related_name='group_notifications', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profiles',
            field=models.ManyToManyField(related_name='profile_notifications', to='commission.UserProfile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipients',
            field=models.ManyToManyField(related_name='user_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='regions',
            field=models.ManyToManyField(related_name='region_notifications', to='account.Region'),
        ),
    ]
