# Generated by Django 3.0.6 on 2021-10-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0010_auto_20211025_1356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmeta',
            options={'permissions': (('manage_notifications', 'Manage notifications.'), ('view_notifications', 'View notifications.')), 'verbose_name': 'notification_meta', 'verbose_name_plural': 'notifications_meta'},
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(default='You have a notification', max_length=64),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('agent_request_submitted', 'Agent request submitted'), ('agent_request_processed', 'Agent request processed'), ('partner_added', 'Partner added'), ('target_set', 'Target set'), ('target_updated', 'Target updated'), ('rule_set', 'Rule set'), ('rule_updated', 'Rule updated'), ('user_correction_request_submitted', 'User correction request submitted'), ('user_correction_request_processed', 'User correction request processed'), ('notice_created', 'Notice created'), ('order_created', 'Order created')], max_length=64),
        ),
    ]
