# Generated by Django 3.0.6 on 2021-10-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0011_auto_20211027_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('agent_request_submitted', 'Agent request submitted'), ('agent_request_processed', 'Agent request processed'), ('kyc_submitted', 'KYC submitted'), ('kyc_processed', 'KYC processed'), ('partner_added', 'Partner added'), ('target_set', 'Target set'), ('target_updated', 'Target updated'), ('rule_set', 'Rule set'), ('rule_updated', 'Rule updated'), ('user_correction_request_submitted', 'User correction request submitted'), ('user_correction_request_processed', 'User correction request processed'), ('notice_created', 'Notice created'), ('order_created', 'Order created')], max_length=64),
        ),
    ]
