# Generated by Django 3.0.6 on 2021-10-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0012_auto_20211031_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',), 'permissions': (('manage_notifications', 'Manage notifications.'), ('view_notifications', 'View notifications.')), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationmeta',
            options={'permissions': (('manage_notification_metas', 'Manage notifications.'),), 'verbose_name': 'notification_meta', 'verbose_name_plural': 'notifications_meta'},
        ),
    ]
