# Generated by Django 3.0.6 on 2021-10-31 17:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0013_auto_20211031_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationmeta',
            unique_together={('notification', 'recipient')},
        ),
    ]
