# Generated by Django 3.0.6 on 2021-10-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0014_auto_20211031_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='private_metadata',
        ),
        migrations.RemoveField(
            model_name='notificationmeta',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='notificationmeta',
            name='private_metadata',
        ),
    ]
