# Generated by Django 3.0.6 on 2020-09-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='redirect_urls',
            field=models.TextField(default='http://localhost:8080/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='root_url',
            field=models.URLField(default='/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='standard_flow_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
