# Generated by Django 3.0.6 on 2020-09-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20200902_0806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('partner_name',), 'permissions': (('manage_partners', 'Manage permissions.'),)},
        ),
    ]
