# Generated by Django 3.0.6 on 2020-09-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_auto_20200903_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('partner_name',), 'permissions': (('manage_partners', 'Manage partners.'),)},
        ),
    ]
