# Generated by Django 3.0.6 on 2020-09-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_auto_20200910_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('partner_name',), 'permissions': (('manage_partners', 'Manage partners.'), ('view_partners', 'View partners.'))},
        ),
    ]
