# Generated by Django 3.0.6 on 2020-10-05 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('partner', '0005_auto_20200927_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.App'),
        ),
    ]
