# Generated by Django 3.0.6 on 2020-10-19 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20201013_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
