# Generated by Django 3.0.6 on 2020-10-22 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_auto_20201019_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('partner_name',), 'permissions': (('manage_partners', 'Manage partners.'),)},
        ),
    ]
