# Generated by Django 3.0.6 on 2021-01-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_auto_20201022_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='access_type',
        ),
        migrations.AddField(
            model_name='partner',
            name='public_client',
            field=models.BooleanField(default=False),
        ),
    ]
