# Generated by Django 3.0.6 on 2021-01-26 04:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0010_auto_20210110_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='call_center_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(code='wrong_phone', message='Please give correct phone number that is like 01*********, 16*** or 096********', regex='(^01[3-9][0-9]{8})|(^096[0-9]{8})|(^16[0-9]{3})$')]),
        ),
    ]
